$ANSIBLE_VAULT;1.1;AES256
37653037323265616437313863653263623633323263313339643932663438663163613534656134
3465303334386466656231363033356633356430346230300a303231363365353664393336366331
63626431626666373036323936643030323766383539393038346437396562633566633833303035
3831623235323234370a333463326265356134396430363737386531346666373961323365303036
38363066353632316538396138616132393766666566323763653231356262323366623034653230
35643333383739306330643662353835616635336138393938333962653964333638383963386133
30356265633236303739393135343138636133633838356637306564666464383262626234336266
64306266616162613733
